version: '3.7'

services: 
  fei:
    environment: 
      llave: ${llave}
      PATH_PREFIX: examenesEscritos
    build: ./IndoorApp
    restart: always
    volumes: 
      - ./IndoorApp:/code
  nginx:
    image: nginx
    restart: always
    volumes: 
      - ./IndoorApp/static:/static/
      - ./IndoorApp/nginx/conf/:/etc/nginx/conf.d/
      - ./certificados:/tmp
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - fei
    ports: 
      - 9000:80
      - 9100:443
    environment: 
      PATH_PREFIX: examenesEscritos

