version: '3.7'

services: 
  fei:
    environment: 
      llave: ${llave}
      PATH_PREFIX: IndoorApp
    build: ./IndoorApp
    restart: always
    volumes: 
      - ./IndoorApp:/code
 
  nginx:
    image: nginx
    restart: always
    volumes: 
      - ./IndoorApp/static:/static/
      - ./IndoorApp/nginx/conf/:/etc/nginx/conf.d/
    depends_on: 
      - fei
    ports: 
      - 9000:80
    environment: 
        PATH_PREFIX: IndoorApp

